name: enumset
description: A Dart implementation EnumSet (or bit fields)
version: 1.0.0
repository: https://github.com/Levi-Lesches/EnumSet-Dart
homepage: https://pub.dev/packages/enumset

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
